disable BrowserStack tests due to flakiness
Running "browserstack_runner" task
Using config: /home/travis/build/twbs/bootstrap/browserstack.json
Launching server on port: 8888
Downloading tunnel jar to `/home/travis/build/twbs/bootstrap/node_modules/browserstack-runner/lib/BrowserStackTunnel.jar`
Launching tunnel
Error: Invalid or corrupt jarfile /home/travis/build/twbs/bootstrap/node_modules/browserstack-runner/lib/BrowserStackTunnel.jar
[Runner alert] Tunnel launch timeout
Exiting
Non existent tunnel